### ISSUE TITLE
Feature: Disregard newlines between function header and body

### ISSUE THREAD

**Issue by Kensei-01** [SnowballSH/Gorilla#12]
I can't use the `{}` brackets in a new line;
e.g.
```js
func hello (any){
println("hello" + any")
}
```

^this works, but when i use:
```js
func hello (any)
{
println(any)
}
```
it returns an error.

**Comment by Samathingamajig** [comment]
@SnowballSH might be similar to the changes that needed to be made for #4

**Comment by SnowballSH** [comment]
Fixed, thanks!
