### ISSUE TITLE
Feature: Right-to-Left parsing for exponentiation operator

### ISSUE THREAD

**Issue by Samathingamajig** [SnowballSH/Gorilla#13]
**Is your feature request related to a problem? Please describe.**

Parsing for the exponentiation operator (`**`) is currently left-to-right, when mathematically it should be right-to-left. This could cause unexpected behavior when someone is implementing an algorithm.

**What type of feature are you requesting?**

Syntax/Parsing Improvement

**Please provide some examples of what Gorilla should be like with your feature.**

Gorilla
![image](https://user-images.githubusercontent.com/29130894/108442806-4d36ff00-721d-11eb-8082-95bc8b439d35.png)
JavaScript
![image](https://user-images.githubusercontent.com/29130894/108442861-62ac2900-721d-11eb-923b-c3c1b2328d55.png)
Python
![image](https://user-images.githubusercontent.com/29130894/108442878-6cce2780-721d-11eb-85bd-5a067a01a2df.png)

**Why should Gorilla have this? Give 2 to 5 reasons.**

Parsing for the exponentiation operator (`**`) is currently left-to-right, when mathematically it should be right-to-left. This could cause unexpected behavior when someone is implementing an algorithm.

**Comment by SnowballSH** [comment]
Wow thanks

**Comment by SnowballSH** [comment]
not sure how to add right-left parsing into gorilla yet, and that is one of the reasons I wanted to start new lol
I'll try. thanks!

**Comment by SnowballSH** [comment]
Close due to 1.0.
